### ISSUE TITLE
23 July 2024 - Open Sourcing AI Readiness at OSFF

### ISSUE THREAD

**Issue by lucaborella89** [finos/ai-readiness#22]
## Date
23 July 2024 - 4pm BST

## What we are trying to achieve
Open sourcing the Simple Governance Framework by OSFF NYC (30th September) 

## Things to be done in preparation to open sourcing the framework at OSFF NYC

1. Cross reference legislations and compare them with Simple Governance Framework

2. Define a future roadmap and work streams

**Comment by lucaborella89** [comment]
@caradelia I have just added this issue to the project board

**Comment by ColinEberhardt** [comment]
superseded by more detailed issues, e.g. #30 #47 #46
