### ISSUE TITLE
[Request Feedback]: TR-2, Insufficient access control with vector store

### ISSUE THREAD

**Issue by vicenteherrera** [finos/ai-readiness#33]
### Contact Details

vicente.herrera@control-plane.io

### What is the idea

This is a request for direct feedback and answers to the following questions regarding a threat described in the governance framework.

**TR-2, Insufficient access control with vector store**
Section: governance-framework/_threats/tr-2.md
File (private repo link): https://github.com/finos/ai-readiness-private/blob/10e31ea7ccf3893983404de3484f7c57f9934d57/governance-framework/_threats/tr-2.md
Diff (private repo link): https://github.com/finos/ai-readiness-private/pull/5/files#diff-db30cd48d424d2b7f0230e21f604f54911fcc66a58c65c610517d8b32fac9a8c

Title: Insufficient access control with vector store
Type: Confidentiality
External references: 
* owasp-llm-top-10
  * LLM06: Sensitive Information Disclosure

Description:
Given the immaturity of the products, the vector store may not have capabilities expected of enterprise software (access control, encryption at rest, audit logging etc). Misconfiguration may allow unauthorized access to data. Internal user accesses data and leaks/tampers it.

**Questions:**
- Original writing of this threat: just related to maturity of new tooling. Is that a sufficient threat?
- Is local vector store poisoning/tampering and/or theft an integrity and confidentiality issue? Is this covered by other frameworks?
- What are the low-level mechanics of poisoning or data extraction from a vector store?

### Why this is important

Discussion surrounding this threat has been going on live, on today's meeting (2024-09-03).

We have opened this issue to better capture's everyone's feedback, and not being constraint by the time alloted to the meeting.

### Code of Conduct

- [X] I agree to follow the FINOS Code of Conduct

**Comment by torinvdb** [comment]
1. Yes, the immaturity of vector store technologies is a sufficient threat to warrant inclusion in the framework. Unlike traditional databases, vector stores are relatively new and are often not equipped with the enterprise-grade security features typically expected, such as robust access control, encryption at rest, and audit logging. Misconfiguration or lack of these controls can lead to unauthorized access, tampering, and data leakage, especially in environments that handle sensitive or proprietary information. The fact that many vector stores are still in developmental stages increases the risk of misconfigurations or incomplete security implementations, making them an easy target for both external and internal threats.

2. The threat associated with vector stores is twofold: integrity and confidentiality. While TR-2 primarily addresses confidentiality concerns, data poisoning and tampering are serious integrity issues that must also be considered. If an attacker or unauthorized internal user gains access to the vector store, they could tamper with or poison the embeddings, which would lead to compromised responses from the RAG model, potentially undermining business processes or steering the model toward erroneous or harmful outputs.

3. From a technical perspective, the mechanics of data extraction and poisoning in a vector store are as follows:

- **Data Extraction**: Vector stores store embeddings, which are high-dimensional representations of data. Without access controls, an attacker can simply query or retrieve these embeddings. By analyzing these vectors, attackers can reverse-engineer or infer the original sensitive data that was used to generate the embeddings. This is especially concerning for embeddings that may represent proprietary algorithms, financial data, or sensitive corporate documents.

- **Poisoning**: In a poisoning attack, an attacker with write access to the vector store could inject false embeddings or modify existing ones. The LLM would then retrieve these tampered embeddings during inference, leading to corrupted or malicious outputs. For example, embedding toxic or misleading data into the vector store could result in biased or harmful recommendations when the LLM performs RAG operations.

_IMO_ LLM + Vector Store = Two Layers of Security. By focusing on both the LLM and vector store in the threat model, we ensure that both inference (LLM) and retrieval (vector store) are secured. Leaving out the vector store would create a blind spot, as attackers could bypass LLM-specific security mechanisms by attacking the data layer.
