### ISSUE TITLE
Formalise our ways of working 

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/ai-readiness#9]
From our in-person workshop:

AI readiness group - what is our expectation for this group?
- Status updates, provide drafts for comment and review
- Recruit core team members

What communication channel? Collaboration tools
- github issues, email distro, zoom
- Zoom meetings / webex
- Docs for collaboration

**Comment by vicenteherrera** [comment]
We discussed communication channels in the last meeting, my proposal including feedback, and some additional information is in this issue:
https://github.com/finos/ai-readiness/issues/23

In the following days I will open a PR with that information.
I'm also proposing making that info public before waiting for OSFF NYC.

**Comment by ColinEberhardt** [comment]
superseded by #47
